# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses.
type: "python:3.7"

# The build-time dependencies of the app.
# dependencies:
#     python3:
#        pipenv: "2018.10.13"

# The hooks executed at various points in the lifecycle of the application.
hooks:
    build: |
      set -e
      # pipenv install --system --deploy
      curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o miniconda.sh

      echo "###########################"
      echo "# Installing Miniconda... #"
      echo "###########################"

      bash miniconda.sh -b -p $HOME/miniconda
      # export PATH="/app/miniconda/bin:$PATH"

      ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh
      . /etc/profile.d/conda.sh

      echo "###########################"
      echo "# Entering Miniconda...   #"
      echo "###########################"
      exit 1

      conda activate base
      conda update -n base -c defaults conda
      conda list

      echo "###########################"
      echo "# Installing mro-base...  #"
      echo "###########################"

      conda create -n mro_env mro-base

      echo "CAT activation file:"
      cat /app/miniconda/envs/mro_env/etc/conda/activate.d/activate-binutils_linux-64.sh
      conda activate mro_env

      echo "Installed R packages:"
      conda list

# The size of the persistent disk of the application (in MB).
disk: 1024
# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    mysql: "mysql:mysql"
    redis: "redis:redis"

# The configuration of app when it is exposed to the web.
web:
    commands:
        start: python server.py
