http://{default}/:
  type: redirect
  to: "https://{default}/"

https://{default}/:
  type: upstream
  upstream: "app:http"
  primary: true
  id: http
  cache:
      enabled: false

http://ws.{default}/:
  type: redirect
  to: "https://ws.{default}/"

https://ws.{default}/:
  type: upstream
  upstream: "app:http"
  id: ws
  cache:
      enabled: false
